[tool.poetry]
name = "trg-multigrid"
version = "0.1.0"
description = "Muti-agent gymnasium gridworld environments"
authors = ["Your Name <you@example.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [{include = "gym_multigrid"}]

[tool.poetry.dependencies]
python = "^3.9"
gymnasium = "^0.26"
matplotlib = "^3.7.1"
numpy = "^1.24.3"
imageio = "^2.28.1"
scikit-learn = "^1.2.2"


[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
